<?php

/**
 * @file
 * Contains external_auth_module.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function external_auth_module_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the external_auth_module module.
    case 'help.page.external_auth_module':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('External authentication module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_FORM_ID_alter()
 */
function external_auth_module_form_user_login_form_alter(&$form, FormStateInterface $form_state, $form_id ) {

  $form['#action'] = '/extauth/login';

}
